title: "王丁春的个人博客"
url: "http://wangdingchun.com"
author: "dcwang"
email: "nostream@163.comm"
description: "dcwang blog"

auto: false
source: .
paginate: 10
paginate_files:
 - index.html


markdown: rdiscount
pygments: true

exclude:
  - README.markdown
  - _drafts
